"""
Import sub-modules so Celery can register their @app.task decorators.
"""

from memory.workers.tasks import (
    backup,
    blogs,
    calendar,
    comic,
    discord,
    ebook,
    email,
    forums,
    github,
    google_drive,
    maintenance,
    meetings,
    metrics,
    notes,
    observations,
    people,
    photo,
    scheduled_calls,
    sessions,
    slack,
    verification,
)  # noqa

__all__ = [
    "backup",
    "blogs",
    "calendar",
    "comic",
    "discord",
    "ebook",
    "email",
    "forums",
    "github",
    "google_drive",
    "maintenance",
    "meetings",
    "metrics",
    "notes",
    "observations",
    "people",
    "photo",
    "scheduled_calls",
    "sessions",
    "slack",
    "verification",
]
